In [1]:
import torch

### 创建tensor
    Tensor提供GPU计算和自动求梯度等更多功能，这些使Tensor更加适合深度学习

In [2]:
# 创建一个5x3的未初始化的Tensor
x = torch.empty((5,3))
x

tensor([[2.7453e-14, 5.3109e-43, 2.7453e-14],
        [5.3109e-43, 2.7453e-14, 5.3109e-43],
        [2.7453e-14, 5.3109e-43, 2.7453e-14],
        [5.3109e-43, 2.7453e-14, 5.3109e-43],
        [2.7453e-14, 5.3109e-43, 2.7453e-14]])

In [3]:
# 创建一个5x3的随机初始化的Tensor
x = torch.rand(5,3)
x

tensor([[0.0615, 0.8938, 0.6958],
        [0.2092, 0.6197, 0.7342],
        [0.8067, 0.5925, 0.6988],
        [0.0456, 0.6773, 0.0826],
        [0.9243, 0.3691, 0.1360]])

In [4]:
# 创建一个5x3的long型全0的Tensor
x = torch.zeros((5,3),dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
# 直接根据数据创建
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [6]:
# 通过现有的Tensor来创建
x = x.new_ones(5,3,dtype=torch.float64) # 返回的tensor默认具有相同的torch.dtype和torch.device
print(x)

x = torch.randn_like(x,dtype=torch.float) # 指定新的数据类型
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.1714, -1.1986,  0.9039],
        [-1.3208,  0.5313,  0.8196],
        [ 1.5630, -0.0634,  0.2514],
        [ 0.2558, -0.2120, -0.6837],
        [ 0.1621,  0.7266, -1.0051]])


In [7]:
# 通过shape或者size()来获取Tensor的形状
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


#### 其他创建方式：
    eye(*sizes)        对角线为1，其他为0
    arange(s,e,step)   从s到e，步长为step
    rand/randn(*sizes) 均匀/标准分布
    normal(mean,std)/uniform(from,to) 正态分布/均匀分布
    randperm(m)        随机排列

### 操作


In [8]:
# 算术操作 
y = torch.rand(5,3)
print(x+y)
torch.add(x,y)
# torch.mul(x,y)
# torch.div(x,y)
# torch.sub(x,y)

tensor([[ 3.7521e-01, -9.9798e-01,  1.7376e+00],
        [-1.0019e+00,  1.2528e+00,  1.3783e+00],
        [ 1.8117e+00,  7.5613e-01,  7.6144e-01],
        [ 8.0492e-01,  4.6593e-01,  4.0054e-04],
        [ 6.7531e-01,  8.4384e-01, -2.1128e-01]])


tensor([[ 3.7521e-01, -9.9798e-01,  1.7376e+00],
        [-1.0019e+00,  1.2528e+00,  1.3783e+00],
        [ 1.8117e+00,  7.5613e-01,  7.6144e-01],
        [ 8.0492e-01,  4.6593e-01,  4.0054e-04],
        [ 6.7531e-01,  8.4384e-01, -2.1128e-01]])

In [9]:
# 索引：可以使用类似NumPy的索引操作来访问Tensor的一部分，需要注意的是：索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改
y = x[0,:]
print(x[0,:])
y += 1
print(y)
print(x[0,:])

tensor([ 0.1714, -1.1986,  0.9039])
tensor([ 1.1714, -0.1986,  1.9039])
tensor([ 1.1714, -0.1986,  1.9039])


#### :
    index_select(input, dim, index) 在指定维度dim上选取，比如选取某些行、某些列
    masked_select(input, mask)      例子如上，a[a>0]，使用ByteTensor进行选取
    nonzero(input)                  非0元素的下标
    gather(input, dim, index)       根据index，在dim维度上选取数据，输出的size与index一样

In [12]:
# 改变tensor形状: view / reshape
y = x.shape
print(y)
z = x.view(-1,5) # -1所指的维度可以根据其他维度的值推出来
# view()返回的新Tensor与源Tensor虽然可能有不同的size，但是是共享data的
print(z.shape)

torch.Size([5, 3])
torch.Size([3, 5])


In [13]:
# 线性代数

#### :
    trace     对角线元素之和(矩阵的迹)
    t         转置
    dot/cross 内积/外积
    svd       奇异值分解

### 广播机制：
    当对两个形状不同的Tensor按元素运算时，可能会触发广播（broadcasting）机制：先适当复制元素使这两个Tensor形状相同后再按元素运算

In [14]:
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(1, 4).view(3, 1)
print(x + y)
# 由于x和y分别是1行2列和3行1列的矩阵，如果要计算x + y，
# 那么x中第一行的2个元素被广播（复制）到了第二行和第三行，而y中第一列的3个元素被广播（复制）到了第二列

tensor([[2, 3],
        [3, 4],
        [4, 5]])


### Tensor和NumPy相互转换
    numpy()和from_numpy(),这两个函数所产生的的Tensor和NumPy中的数组共享相同的内存
    
    torch.tensor()将NumPy数组转换成Tensor,该方法总是会进行数据拷贝，返回的Tensor和原来的数据不再共享内存

In [18]:
# Tensor -> numpy 数组
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
a += 1
print(a,b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [19]:
# numpy 数组 -> Tensor
import numpy as np
c = np.ones(5)
print(c)
d = torch.from_numpy(c)
print(d)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [22]:
e = torch.tensor(c) # 返回的Tensor和原来的数据不再共享内存
print(c,e)
e += 1
print(c,e)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[1. 1. 1. 1. 1.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### Tensor on GPU
    用方法to()可以将Tensor在CPU和GPU（需要硬件支持）之间相互移动